name: Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Derruba o contêiner Docker em execução
      - name: Stop running container
        run: |
          CONTAINER_ID=$(docker ps -q --filter "name=forecastusd")
          if [ ! -z "$CONTAINER_ID" ]; then
            docker stop $CONTAINER_ID
          fi

      # Constrói a nova imagem Docker
      - name: Build Docker image
        run: docker build -t forecastusd:latest .

      # Executa o novo contêiner Docker
      - name: Run Docker container
        run: docker run -d -p 80:80 --name forecastusd forecastusd:latest
